### ISSUE TITLE
Notebook Settings => AttributeError

### ISSUE THREAD

**Issue by derkan** [ShadowKyogre/mikidown#43]
Hi,
Thanks for nice editor I was looking for.
I cloned from github and run with python3(3.4.0). Notebook Settings page is raising exception:
 
```
Traceback (most recent call last):
  File "/home/erkan/Installs/mikidown/mikidown/mikiwindow.py", line 587, in notebookSettings
    dialog = NotebookSettingsDialog(self)
  File "/home/erkan/Installs/mikidown/mikidown/mikibook.py", line 137, in __init__
    self.initExtList()
  File "/home/erkan/Installs/mikidown/mikidown/mikibook.py", line 199, in initExtList
    for ext in allMDExtensions():
  File "/home/erkan/Installs/mikidown/mikidown/utils.py", line 86, in allMDExtensions
    if pkgutil.find_loader(m[1][4:]) is None:
  File "/usr/lib/python3.4/pkgutil.py", line 488, in find_loader
    return spec.loader
AttributeError: 'NoneType' object has no attribute 'loader'
```
Regards
derkan

**Comment by ShadowKyogre** [comment]
Closing until more information is provided.
